### ISSUE TITLE
from model import _C failed No name '_C' in module 'model'

### ISSUE THREAD

**Issue by djp1235a** [McDo/PSROIAlign-Multi-Batch-PyTorch#2]
running build_ext
building 'model._C' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/djp
creating build/temp.linux-x86_64-3.6/home/djp/github
creating build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch
creating build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model
creating build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc
creating build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda
gcc -pthread -B /home/djp/anaconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/TH -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/djp/anaconda3/envs/pytorch/include/python3.6m -c /home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/TH -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/djp/anaconda3/envs/pytorch/include/python3.6m -c /home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIPool_cuda.cu -o build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIPool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/local/cuda/bin/nvcc -DWITH_CUDA -I/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/TH -I/home/djp/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/djp/anaconda3/envs/pytorch/include/python3.6m -c /home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIAlign_cuda.cu -o build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/model
g++ -pthread -shared -B /home/djp/anaconda3/envs/pytorch/compiler_compat -L/home/djp/anaconda3/envs/pytorch/lib -Wl,-rpath=/home/djp/anaconda3/envs/pytorch/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/vision.o build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIPool_cuda.o build/temp.linux-x86_64-3.6/home/djp/github/PSROIAlign-Multi-Batch-PyTorch/model/csrc/cuda/PSROIAlign_cuda.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/model/_C.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/model/_C.cpython-36m-x86_64-linux-gnu.so -> model

**Comment by McDo** [comment]
hi @djp1235a ,did you registered a global **model** module in you path?

**Comment by djp1235a** [comment]
Thank you @McDo
