### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by DayBreak-u** [McDo/PSROIAlign-Multi-Batch-PyTorch#3]
hi: DO you do the cpu infer?

**Comment by McDo** [comment]
@ouyanghuiyu not yet, the latest torchvision has had a complete implementation, you may check it out.

**Comment by DayBreak-u** [comment]
thanks! but I didn't find psroialign in torchvision==0.4.2. could you tell me which the funtion

**Comment by McDo** [comment]
https://github.com/pytorch/vision/tree/master/torchvision/csrc

**Comment by DayBreak-u** [comment]
thanks
